<Workspace Version="1.3.4.6666" X="202.990670416275" Y="195.689118550411" zoom="0.448907884831097" ScaleFactor="1" Name="Convert from SurveyPoint CoordinateSystem" Description="Convert from Survey Coordinate to Internal Origin Coordinate." ID="10f202e9-2198-43dc-8632-242ca8b2c7d6" Category="GeniusLoci.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="CoordinateSystem" resolvedName="Autodesk.DesignScript.Geometry.CoordinateSystem" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Coordinates" resolvedName="Revit.Elements.Coordinates" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry" resolvedName="Autodesk.DesignScript.Geometry.Geometry" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Geometry" resolvedName="Autodesk.DesignScript.Geometry.Geometry" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="46e1036b-af6f-4866-bfe7-231b38412be7" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="144" y="237" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="coordinate = CoordinateSystem.Rotate(CoordinateSystem.ByOrigin(bp[0]), bp[0], Autodesk.DesignScript.Vector.ZAxis(), 360 - bp[1]);&#xA;coordinate2 = CoordinateSystem.ByOrigin(Coordinates.BasePoint());&#xA;Autodesk.DesignScript.Geometry.Transform(point, coordinate, coordinate2);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="2e229fe5-3481-4ce1-8ba7-72228724ee8d" type="PythonNodeModels.PythonNode" nickname="Get BasePoint" x="-94.5763412477496" y="191.935006341013" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Alban de Chasteigner 2020
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com
#https://github.com/albandechasteigner/GeniusLociForDynamo

import clr
clr.AddReference("RevitServices")
import RevitServices 
from RevitServices.Persistence import DocumentManager
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
version=int(app.VersionNumber)

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import Document, UnitType, FilteredElementCollector, BuiltInCategory, XYZ

doc = DocumentManager.Instance.CurrentDBDocument

angleUnit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Angle).DisplayUnits

outProjBasePt = []

pbp = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_ProjectBasePoint).ToElements()

if version &lt; 2018:
	projPos = doc.ActiveProjectLocation.get_ProjectPosition(XYZ(0,0,0))
else :
	projPos = doc.ActiveProjectLocation.GetProjectPosition(XYZ(0,0,0))
	
if version &gt; 2019 :
	outProjBasePt = [pbp[0].SharedPosition.ToPoint(),abs(round(Autodesk.Revit.DB.UnitUtils.ConvertFromInternalUnits(projPos.Angle,angleUnit),6))]
else :
	pbpEW = pbp[0].get_Parameter(BuiltInParameter.BASEPOINT_EASTWEST_PARAM).AsDouble()
	pbpNS = pbp[0].get_Parameter(BuiltInParameter.BASEPOINT_NORTHSOUTH_PARAM).AsDouble()
	pbpElev = pbp[0].get_Parameter(BuiltInParameter.BASEPOINT_ELEVATION_PARAM).AsDouble()
	pbpAngle = pbp[0].get_Parameter(BuiltInParameter.BASEPOINT_ANGLETON_PARAM).AsDouble()*180/math.pi    
	outProjBasePt=[(XYZ(pbpEW,pbpNS,pbpElev)).ToPoint(),round(pbpAngle,6)]
	
OUT = outProjBasePt</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c3899592-6430-4ef5-be9d-840eaf908844" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-353.78870571519" y="277.533658626108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Point in Survey Coordinate System&#xD;&#xA;point: Autodesk.DesignScript.Geometry.Point[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="c3080e04-615e-475a-9b88-1c5fac9ef6d4" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="963.507614940748" y="269.82011297745" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//Point in Internal Origin Coordinate System&#xD;&#xA;Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="46e1036b-af6f-4866-bfe7-231b38412be7" start_index="2" end="c3080e04-615e-475a-9b88-1c5fac9ef6d4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2e229fe5-3481-4ce1-8ba7-72228724ee8d" start_index="0" end="46e1036b-af6f-4866-bfe7-231b38412be7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c3899592-6430-4ef5-be9d-840eaf908844" start_index="0" end="46e1036b-af6f-4866-bfe7-231b38412be7" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>