<Workspace Version="1.3.4.6666" X="89.3493703722834" Y="172.040668212171" zoom="0.372503509634529" ScaleFactor="1" Name="Convert from ProjectBasePoint CoordinateSystem" Description="Convert from Project Base Point Coordinate to Internal Origin Coordinate." ID="37e09dbf-5a10-4918-9de0-0ebabf93c071" Category="GeniusLoci.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="CoordinateSystem" resolvedName="Autodesk.DesignScript.Geometry.CoordinateSystem" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Coordinates" resolvedName="Revit.Elements.Coordinates" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry" resolvedName="Autodesk.DesignScript.Geometry.Geometry" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Geometry" resolvedName="Autodesk.DesignScript.Geometry.Geometry" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="740bd1df-fc2f-4928-aee5-e3cc4f652782" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="129" y="207" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="geometry1 = Autodesk.DesignScript.Geometry.Transform(point, CoordinateSystem.Identity(), CoordinateSystem.ByOrigin(Coordinates.BasePoint()));" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="543d9003-8c8a-4003-8f6f-a127dd291194" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-351.315555867322" y="202.247543519873" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Point in Project BasePoint Coordinate System&#xD;&#xA;point: Autodesk.DesignScript.Geometry.Point[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5e13bfc4-36be-4d08-9501-96436d7d2eb9" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="941.533464631644" y="204.381100329959" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//Point in Internal Origin Coordinate System&#xD;&#xA;Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="740bd1df-fc2f-4928-aee5-e3cc4f652782" start_index="0" end="5e13bfc4-36be-4d08-9501-96436d7d2eb9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="543d9003-8c8a-4003-8f6f-a127dd291194" start_index="0" end="740bd1df-fc2f-4928-aee5-e3cc4f652782" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>